### ISSUE TITLE
Wrong error message on minting token in case of insufficient funds

### ISSUE THREAD

**Issue by sarora180673** [rairprotocol/rair-dapp#232]
Latest dev branch

Test case :  Try to mint token using Metamask  from Collection Page using account which has insufficient balance

Observation :  On clicking Purchase Button, getting "when several people .... "  error instead of insufficient funds error

![Screenshot from 2024-09-28 16-38-27](https://github.com/user-attachments/assets/a2b34605-c64e-4464-ac98-94f6665aeebf)

**Comment by Jomossey** [comment]
@sarora180673 Seems like there's a mix-up in the error message you're receiving when trying to mint a token using Metamask from the Collection Page with an account that has insufficient balance. Instead of the expected "insufficient funds" error, you're getting a different message. This could be due to a configuration issue or a specific error handling setup. I'll have to refer you to the official support live chat with the ticket ID MET07638
Please see the link below to our dedicated support line:
[Metamask Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.
